#!/bin/bash
################################
# Chord Finder launcher script #
################################

script=$(readlink -f $0)
scriptpath=`dirname $script`

if [ "$scriptpath" == '/usr/bin' ] ; then
    # Installed
    python /usr/lib/python2.7/site-packages/chord_finder/ChordFinder.py
else
    # Not installed
    python src/ChordFinder.py
fi

