#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" Main chord-finder entry point """

import wx, os

from chordfinder import ChordData, DrawChord, DrawRootFinder, Instruments, Palettes, Gui

CONFIG = {}

CONFIG['VERSION'] = '0.9'

CONFIG['data_dir'] = '/etc/chord-finder/'

#################
#### MAIN () ####
#################
CHORD_DB = ChordData.ChordDatabase(CONFIG['data_dir']+'ChordData.csv')
APP = wx.PySimpleApp(0)
wx.InitAllImageHandlers()
MAIN_FRAME = Gui.MainFrame(None, -1, "", CHORD_DB, CONFIG)
APP.SetTopWindow(MAIN_FRAME)
MAIN_FRAME.Show()
MAIN_FRAME.Centre()
APP.MainLoop()
